# Generated by Django 5.1.5 on 2025-02-18 08:34

import django_ltree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numchild',
        ),
        migrations.AlterField(
            model_name='item',
            name='path',
            field=django_ltree.fields.PathField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'), ('de-de', 'German'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
