# Generated by Django 5.1.5 on 2025-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_mimetype_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_workspace',
            field=models.BooleanField(default=False),
        ),
    ]
