# Generated by Django 5.1.5 on 2025-02-21 16:24

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_options_remove_item_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='numchild_folder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='folder', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'), ('de-de', 'German'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='drive_item_path_a306e2_gist'),
        ),
    ]
