# Generated by Django 5.1.5 on 2025-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_main_workspace_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
