# Generated by Django 5.1.8 on 2025-04-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '00006_create_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hard_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
